#!/usr/bin/env python3
# ****************************************************************************************************************************************************
# * BSD 3-Clause License
# *
# * Copyright (c) 2026, Mana Battery ApS
# * All rights reserved.
# *
# * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
# *
# * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the
# *    documentation and/or other materials provided with the distribution.
# * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this
# *    software without specific prior written permission.
# *
# * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# ****************************************************************************************************************************************************

# The content of the CMakePresets.json of a generated CMake project.
#
# The presets let anything that reads CMake presets configure and build the generated project the way FslBuild does it:
#   cmake --preset default, cmake --build --preset debug, cmake --workflow --preset debug
#
# A configure preset is a translation of the configure command the tool runs itself (see Generator/Report/ResolvedConfigCommand.py), it is
# not made from the settings a second time: what the command does not say is not in the preset, and a command with an argument a preset has
# no field for gives no presets at all, as a preset that configures something else than the tool is worse than none.
#
# This module holds no file system access and starts no process: the commands, the environment and the texts come in as plain data and the
# content of the file comes out. Generator/CMakePresetsFile.py collects the data and writes the file.
#
# The format is the one of 'cmake --help-manual cmake-presets'. What was checked with CMake 4.4.3:
# - binaryDir, installDir, toolchainFile, the values of cacheVariables and the values of environment are macro expanded, so a '$' in them
#   is written as '${dollar}'. generator, architecture, toolset and the names of variables are used as they are written.
# - a string in cacheVariables is the same as '-D<name>=<value>', an object with a type the same as '-D<name>:<type>=<value>'.
# - a build preset gets the environment of its configure preset.
# - the command line drops white space at the end of the value of '-D' and single quotes around it, a preset keeps both.
#
# A limit: when a variable is given without a type and the project declares it as a path, cmake turns a relative value into an absolute
# one from the directory cmake is run in. The tool runs its configure in the build directory and a preset is used from anywhere, so such a
# value can mean another directory there. The tool passes no such value itself, one a user adds to the configure arguments is not seen
# (only the install prefix is known to be such a path: a relative one gives no presets).

import json
import re
from collections.abc import Mapping, Sequence

from FslBuildGen import PathCompare

FileName = "CMakePresets.json"

# The version of the format: the first one that knows '$comment'
FormatVersion = 10
# The first CMake that reads that version
MinimumCMakeVersion = (3, 31, 0)

# The schema of the format. The manual gives it as a download of the documentation ('manual/presets/schema.json'), this is where the
# html manual links to.
SchemaUrl = "https://cmake.org/cmake/help/latest/_downloads/3e2d73bff478d88a7de0de736ba5e361/schema.json"

# The key of the vendor entry that marks a file as written by the tool, named as the manual asks for: a domain followed by a path
VendorName = "manabattery.com/FslBuildGen"

Comment = [
    "Generated by FslBuildGen and written again on every generation: do not edit.",
    "The presets configure and build this project the way FslBuild does. Put your own presets in CMakeUserPresets.json.",
]

# What a group of configurations that share a configure command is called
DefaultPresetName = "default"

_g_cacheTypes = ("BOOL", "FILEPATH", "PATH", "STRING", "INTERNAL")
_g_installPrefixName = "CMAKE_INSTALL_PREFIX"
_g_toolchainFileName = "CMAKE_TOOLCHAIN_FILE"
_g_windowsAbsolutePath = re.compile(r"^[A-Za-z]:[\\/]")
# Up to Visual Studio 2017 the platform could be part of the generator name
_g_visualStudioWithPlatform = re.compile(r"^Visual Studio \d+ \d+ \S+$")


class CanNotBeExpressedException(Exception):
    """The configure command does something a preset can not say"""


class PresetConfiguration:
    """An option of the config variant ('Debug') and the configure command the tool runs for it"""

    def __init__(self, name: str, buildConfiguration: str | None, command: Sequence[str], workingDirectory: str) -> None:
        super().__init__()
        self.Name = name
        # What the build is given as '--config', None when the configure command decides the configuration
        self.BuildConfiguration = buildConfiguration
        # The program followed by its arguments
        self.Command = list(command)
        # The directory the command is run in: the build directory
        self.WorkingDirectory = workingDirectory


class PresetsInput:
    def __init__(
        self,
        cmakeVersion: tuple[int, int, int],
        cmakeCommand: str,
        sourceDirectory: str,
        platformName: str,
        configurations: Sequence[PresetConfiguration],
        environment: Mapping[str, str],
        variants: Sequence[tuple[str, str]],
    ) -> None:
        """
        cmakeCommand: the cmake program as the tool runs it. A configure command that starts with another program can not be a preset.
        sourceDirectory: the directory of the top-level CMakeLists.txt, the file is written there.
        configurations: the configurations to make presets for, in the order of the config variant.
        environment: the environment variables the project reads with their values, for the configure presets.
        variants: the variant and flavor options the project was generated with (name, option), for the descriptions.
        """
        super().__init__()
        self.CMakeVersion = cmakeVersion
        self.CMakeCommand = cmakeCommand
        self.SourceDirectory = sourceDirectory
        self.PlatformName = platformName
        self.Configurations = list(configurations)
        self.Environment = dict(environment)
        self.Variants = list(variants)


class PresetsResult:
    def __init__(self, content: dict[str, object] | None, reason: str) -> None:
        super().__init__()
        # The content of the file, None when there is to be no file
        self.Content = content
        # Why there is to be no file
        self.Reason = reason


class ConfigureSettings:
    """What a configure command sets, by the field of a configure preset that says it"""

    def __init__(self, binaryDir: str) -> None:
        super().__init__()
        self.Generator: str | None = None
        self.Architecture: str | None = None
        self.Toolset: str | None = None
        self.BinaryDir = binaryDir
        self.InstallDir: str | None = None
        self.ToolchainFile: str | None = None
        # name -> (type, value) in the order of the command, the type is None for a variable that is given without one
        self.CacheVariables: dict[str, tuple[str | None, str]] = {}


def IsAbsolutePath(path: str) -> bool:
    """True if the path does not depend on a current directory, in the notation of any platform"""
    return path.startswith(("/", "\\\\")) or _g_windowsAbsolutePath.match(path) is not None


def _ParseCacheArgument(shownArgument: str, text: str) -> tuple[str, str | None, str]:
    """The name, type and value of '<name>=<value>' or '<name>:<type>=<value>', split the way cmake splits it"""
    separatorIndex = text.find("=")
    if separatorIndex < 0:
        raise CanNotBeExpressedException(f"the argument '{shownArgument}' gives the variable no value")
    name, typeSeparator, typeName = text[:separatorIndex].partition(":")
    value = text[separatorIndex + 1 :]
    if len(name) == 0 or name.startswith('"'):
        raise CanNotBeExpressedException(f"the argument '{shownArgument}' has no plain variable name")
    if len(typeSeparator) > 0 and typeName not in _g_cacheTypes:
        raise CanNotBeExpressedException(f"the argument '{shownArgument}' has the unknown type '{typeName}'")
    # What cmake does to the value of a '-D' argument and not to the value in a preset
    strippedValue = value.rstrip(" \t\r")
    if len(strippedValue) > 0 and strippedValue != value:
        raise CanNotBeExpressedException(f"the argument '{shownArgument}' ends with white space, which the command line drops and a preset keeps")
    if len(value) >= 2 and value.startswith("'") and value.endswith("'"):
        raise CanNotBeExpressedException(f"the argument '{shownArgument}' has its value in single quotes, which the command line removes and a preset keeps")
    return (name, typeName if len(typeSeparator) > 0 else None, value)


def _RequireAbsolutePath(shownArgument: str, path: str) -> None:
    if not IsAbsolutePath(path):
        raise CanNotBeExpressedException(f"the argument '{shownArgument}' holds the relative path '{path}', which a preset reads from another directory")


def TranslateConfigureCommand(command: Sequence[str], workingDirectory: str, cmakeCommand: str, sourceDirectory: str) -> ConfigureSettings:
    """Translate a configure command ('cmake -D<name>=<value> ... -G <generator> <source directory>') that is run in workingDirectory.
    Raises CanNotBeExpressedException for a command a preset can not say exactly.
    """
    if len(command) == 0 or command[0] != cmakeCommand:
        program = command[0] if len(command) > 0 else ""
        raise CanNotBeExpressedException(f"the configure command is run by '{program}' and a preset is run by cmake itself")
    sourceArgument = command[-1] if len(command) > 1 else ""
    if not PathCompare.IsSamePath(sourceArgument, sourceDirectory):
        raise CanNotBeExpressedException(f"the configure command ends with '{sourceArgument}' and not with the directory of the presets '{sourceDirectory}'")
    if not IsAbsolutePath(workingDirectory):
        raise CanNotBeExpressedException(f"the configure command is run in the relative directory '{workingDirectory}'")

    settings = ConfigureSettings(workingDirectory)
    arguments = command[1:-1]
    given: set[str] = set()
    index = 0
    while index < len(arguments):
        argument = arguments[index]
        kind = argument[:2]
        if kind not in ("-D", "-G", "-A", "-T"):
            raise CanNotBeExpressedException(f"the argument '{argument}' of the configure command has no field in a preset")
        value = argument[2:]
        shownArgument = argument
        if len(value) == 0:
            # The value is the next argument
            index += 1
            if index >= len(arguments):
                raise CanNotBeExpressedException(f"the argument '{argument}' of the configure command has no value")
            value = arguments[index]
            shownArgument = f"{argument} {value}"
        index += 1

        if kind == "-D":
            name, typeName, variableValue = _ParseCacheArgument(shownArgument, value)
            # The last one of a variable that is given twice counts, as on the command line
            settings.CacheVariables.pop(name, None)
            settings.CacheVariables[name] = (typeName, variableValue)
            continue
        if kind in given:
            raise CanNotBeExpressedException(f"the configure command has more than one '{kind}' argument")
        given.add(kind)
        if kind == "-G":
            if _g_visualStudioWithPlatform.match(value) is not None:
                raise CanNotBeExpressedException(f"the generator '{value}' names its platform, which a preset does not allow")
            settings.Generator = value
        elif kind == "-A":
            settings.Architecture = value
        else:
            settings.Toolset = value

    # The two variables a preset has a field of its own for.
    installPrefix = settings.CacheVariables.get(_g_installPrefixName)
    if installPrefix is not None and installPrefix[0] in (None, "PATH"):
        # installDir reads a relative path from the source directory, the command line does not
        _RequireAbsolutePath(f"-D{_g_installPrefixName}={installPrefix[1]}", installPrefix[1])
        settings.InstallDir = installPrefix[1]
        del settings.CacheVariables[_g_installPrefixName]
    toolchainFile = settings.CacheVariables.get(_g_toolchainFileName)
    if toolchainFile is not None and toolchainFile[0] in (None, "FILEPATH"):
        # A relative toolchain file is looked for in the build directory and then in the source directory, by the field and the variable
        settings.ToolchainFile = toolchainFile[1]
        del settings.CacheVariables[_g_toolchainFileName]
    return settings


def EscapeMacros(text: str) -> str:
    """The text for a field that is macro expanded: a '$' would start a macro there"""
    return text.replace("$", "${dollar}")


class _ConfigureGroup:
    """The configurations that are configured by the same command, they share a configure preset"""

    def __init__(self, settings: ConfigureSettings, configuration: PresetConfiguration) -> None:
        super().__init__()
        self.Settings = settings
        self.Configurations = [configuration]
        self.Name = ""


def _ToPresetName(configuration: PresetConfiguration) -> str:
    return configuration.Name.lower()


def _RequireUniqueNames(names: Sequence[str], kind: str) -> None:
    if len(set(names)) != len(names):
        raise CanNotBeExpressedException(f"two {kind} presets would get the same name: {', '.join(names)}")


def _GroupByConfigureCommand(source: PresetsInput) -> list[_ConfigureGroup]:
    groups: dict[tuple[tuple[str, ...], str], _ConfigureGroup] = {}
    for configuration in source.Configurations:
        key = (tuple(configuration.Command), configuration.WorkingDirectory)
        group = groups.get(key)
        if group is not None:
            group.Configurations.append(configuration)
        else:
            settings = TranslateConfigureCommand(configuration.Command, configuration.WorkingDirectory, source.CMakeCommand, source.SourceDirectory)
            groups[key] = _ConfigureGroup(settings, configuration)

    result = list(groups.values())
    sharedGroupCount = len([group for group in result if len(group.Configurations) > 1])
    for group in result:
        names = [_ToPresetName(configuration) for configuration in group.Configurations]
        group.Name = names[0] if len(names) == 1 else (DefaultPresetName if sharedGroupCount == 1 else "-".join(names))
    _RequireUniqueNames([group.Name for group in result], "configure")
    _RequireUniqueNames([_ToPresetName(configuration) for configuration in source.Configurations], "build")
    return result


def _JoinNames(names: Sequence[str]) -> str:
    """'A', 'A and B', 'A, B and C'"""
    return names[0] if len(names) == 1 else f"{', '.join(names[:-1])} and {names[-1]}"


def _DescribeProject(source: PresetsInput, settings: ConfigureSettings) -> str:
    """Which project this is: the same package can be generated for several platforms, generators and variant options"""
    generator = f"the generator '{settings.Generator}'" if settings.Generator is not None else "the default generator"
    if len(source.Variants) > 0:
        variants = "--Variants [{}]".format(",".join(f"{name}={option}" for name, option in source.Variants))
    else:
        variants = "no --Variants"
    return f"the project FslBuildGen generated for the platform {source.PlatformName} with {generator} and {variants}"


def _DisplayName(source: PresetsInput, settings: ConfigureSettings, configurationNames: Sequence[str]) -> str:
    generator = settings.Generator if settings.Generator is not None else "default generator"
    return f"{source.PlatformName} {generator} ({', '.join(configurationNames)})"


def _CreateConfigurePreset(source: PresetsInput, group: _ConfigureGroup) -> dict[str, object]:
    settings = group.Settings
    configurationNames = [configuration.Name for configuration in group.Configurations]
    preset: dict[str, object] = {
        "name": group.Name,
        "displayName": _DisplayName(source, settings, configurationNames),
        "description": f"Configures {_JoinNames(configurationNames)} of {_DescribeProject(source, settings)}.",
    }
    if settings.Generator is not None:
        preset["generator"] = settings.Generator
    if settings.Architecture is not None:
        preset["architecture"] = settings.Architecture
    if settings.Toolset is not None:
        preset["toolset"] = settings.Toolset
    preset["binaryDir"] = EscapeMacros(settings.BinaryDir)
    if settings.InstallDir is not None:
        preset["installDir"] = EscapeMacros(settings.InstallDir)
    if settings.ToolchainFile is not None:
        preset["toolchainFile"] = EscapeMacros(settings.ToolchainFile)
    if len(settings.CacheVariables) > 0:
        cacheVariables: dict[str, object] = {}
        for name, (typeName, value) in settings.CacheVariables.items():
            cacheVariables[name] = EscapeMacros(value) if typeName is None else {"type": typeName, "value": EscapeMacros(value)}
        preset["cacheVariables"] = cacheVariables
    if len(source.Environment) > 0:
        # Sorted so the file does not depend on the order the variables were found in
        preset["environment"] = {name: EscapeMacros(source.Environment[name]) for name in sorted(source.Environment, key=lambda name: (name.lower(), name))}
    return preset


def TryCreate(source: PresetsInput) -> PresetsResult:
    """The content of the presets file, or the reason there can not be one"""
    if source.CMakeVersion < MinimumCMakeVersion:
        version = ".".join(str(entry) for entry in source.CMakeVersion)
        minimumVersion = ".".join(str(entry) for entry in MinimumCMakeVersion[:2])
        return PresetsResult(None, f"CMake {version} does not read version {FormatVersion} of the presets format, that takes CMake {minimumVersion} or newer")
    if len(source.Configurations) == 0:
        return PresetsResult(None, "there is no configuration to make a preset for")
    try:
        groups = _GroupByConfigureCommand(source)
    except CanNotBeExpressedException as ex:
        return PresetsResult(None, str(ex))

    configurePresets: list[dict[str, object]] = []
    buildPresets: list[dict[str, object]] = []
    workflowPresets: list[dict[str, object]] = []
    for group in groups:
        configurePresets.append(_CreateConfigurePreset(source, group))
    # The build and workflow presets are in the order of the config variant
    for configuration in source.Configurations:
        group = next(entry for entry in groups if configuration in entry.Configurations)
        name = _ToPresetName(configuration)
        displayName = _DisplayName(source, group.Settings, [configuration.Name])
        project = _DescribeProject(source, group.Settings)
        buildPreset: dict[str, object] = {
            "name": name,
            "displayName": displayName,
            "description": f"Builds {configuration.Name} of {project}.",
            "configurePreset": group.Name,
        }
        if configuration.BuildConfiguration is not None:
            buildPreset["configuration"] = configuration.BuildConfiguration
        buildPresets.append(buildPreset)
        workflowPresets.append(
            {
                "name": name,
                "displayName": displayName,
                "description": f"Configures and builds {configuration.Name} of {project}.",
                "steps": [{"type": "configure", "name": group.Name}, {"type": "build", "name": name}],
            }
        )

    content: dict[str, object] = {
        "$schema": SchemaUrl,
        "$comment": list(Comment),
        "version": FormatVersion,
        "vendor": {VendorName: {"generated": True}},
        "configurePresets": configurePresets,
        "buildPresets": buildPresets,
        "workflowPresets": workflowPresets,
    }
    return PresetsResult(content, "")


def ToText(content: Mapping[str, object]) -> str:
    """The text of the file: the same content always gives the same text. It is ASCII, so it does not depend on an encoding."""
    return json.dumps(content, indent=2) + "\n"


def IsWrittenByTheTool(text: str) -> bool:
    """True if the text of a presets file has the vendor entry of the tool, so it is one the tool wrote and may write again or remove"""
    try:
        content = json.loads(text)
    except ValueError:
        return False
    if not isinstance(content, dict):
        return False
    vendor = content.get("vendor")
    return isinstance(vendor, dict) and VendorName in vendor
