#!/usr/bin/env python3
# ****************************************************************************************************************************************************
# * BSD 3-Clause License
# *
# * Copyright (c) 2026, Mana Battery ApS
# * All rights reserved.
# *
# * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
# *
# * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the
# *    documentation and/or other materials provided with the distribution.
# * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this
# *    software without specific prior written permission.
# *
# * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# ****************************************************************************************************************************************************

import xml.etree.ElementTree as ET
from typing import final

from FslBuildGen.DataTypes import PackageLanguage, VisualStudioVersion
from FslBuildGen.Exceptions import UsageErrorException
from FslBuildGen.VisualStudioSolutionFormat import VisualStudioSolutionFormat

# The build .bat template token that is replaced with the solution file name
PROJECT_SOLUTION_FILE_TOKEN = "##PROJECT_SOLUTION_FILE##"

# Marks a .slnx as generated, so a solution saved by Visual Studio is never mistaken for one of ours
GENERATED_MARKER = "AUTOGENERATED by FslBuildGen"

# The solution folder the dependencies are placed in, like the 'Libs' folder of the .sln templates
DEPENDENCY_FOLDER = "/Libs/"

# The build types and platform of the C# projects, the same as the .sln templates use
_BUILD_TYPES = ["Debug", "Release"]
_PLATFORM = "Any CPU"


@final
class SlnxProject:
    def __init__(self, path: str, folder: str | None, buildTypeMap: list[tuple[str, str]]) -> None:
        super().__init__()
        # The project file path relative to the solution, '/' separated
        self.Path = path
        # The solution folder the project is placed in or None for the solution root
        self.Folder = folder
        # (solution variant name, project variant name) for the solution variants the project builds with a differently named variant
        self.BuildTypeMap = buildTypeMap


def CheckSolutionFormatSupported(solutionFormat: VisualStudioSolutionFormat, vsVersion: int, packageLanguage: PackageLanguage) -> None:
    if solutionFormat != VisualStudioSolutionFormat.Slnx:
        return
    formatName = VisualStudioSolutionFormat.ToString(solutionFormat)
    if vsVersion < VisualStudioVersion.VS2026:
        raise UsageErrorException(
            f"Project.gen CompilerConfiguration 'VisualStudio' SolutionFormat='{formatName}' requires Visual Studio {VisualStudioVersion.VS2026}, "
            f"this build uses Visual Studio {vsVersion}"
        )
    if packageLanguage != PackageLanguage.CSharp:
        # The C++ templates use the x64 platform and build dependencies which this writer does not produce
        raise UsageErrorException(f"Project.gen CompilerConfiguration 'VisualStudio' SolutionFormat='{formatName}' is only supported for C# projects")


def CheckBuildBatTemplate(solutionFormat: VisualStudioSolutionFormat, templateBuildBat: str | None, templateFileName: str) -> None:
    """The build .bat template has to build the solution file the generator writes"""
    if solutionFormat != VisualStudioSolutionFormat.Slnx or templateBuildBat is None:
        return
    if PROJECT_SOLUTION_FILE_TOKEN not in templateBuildBat:
        raise UsageErrorException(
            f"The build template '{templateFileName}' does not use {PROJECT_SOLUTION_FILE_TOKEN}, which is required for "
            f"SolutionFormat='{VisualStudioSolutionFormat.ToString(solutionFormat)}'. Replace '##PROJECT_NAME##.sln' with {PROJECT_SOLUTION_FILE_TOKEN}"
        )


def BuildSlnx(solutionVariantNames: list[str], projects: list[SlnxProject]) -> str:
    """Create the content of a .slnx solution.
    Without variants the solution uses the slnx default configurations (Debug and Release with the 'Any CPU' platform).
    """
    root = ET.Element("Solution")
    root.append(ET.Comment(f" {GENERATED_MARKER}, any manual changes to it will be lost if it is regenerated. "))
    if len(solutionVariantNames) > 0:
        configurations = ET.SubElement(root, "Configurations")
        for variantName in solutionVariantNames:
            for buildType in _BUILD_TYPES:
                ET.SubElement(configurations, "BuildType", {"Name": f"{variantName}{buildType}"})
        ET.SubElement(configurations, "Platform", {"Name": _PLATFORM})

    folderDict: dict[str, ET.Element] = {}
    for project in projects:
        if project.Folder is not None and project.Folder not in folderDict:
            folderDict[project.Folder] = ET.SubElement(root, "Folder", {"Name": project.Folder})

    for project in projects:
        parent = root if project.Folder is None else folderDict[project.Folder]
        projectElement = ET.SubElement(parent, "Project", {"Path": project.Path})
        for solutionVariantName, projectVariantName in project.BuildTypeMap:
            for buildType in _BUILD_TYPES:
                ET.SubElement(projectElement, "BuildType", {"Solution": f"{solutionVariantName}{buildType}|*", "Project": f"{projectVariantName}{buildType}"})

    ET.indent(root, space="  ")
    return ET.tostring(root, encoding="unicode") + "\n"
