#!/usr/bin/env python3
# ****************************************************************************************************************************************************
# * BSD 3-Clause License
# *
# * Copyright (c) 2026, Mana Battery ApS
# * All rights reserved.
# *
# * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
# *
# * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the
# *    documentation and/or other materials provided with the distribution.
# * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this
# *    software without specific prior written permission.
# *
# * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# ****************************************************************************************************************************************************

import hashlib

from FslBuildGen.BuildExternal.ConanProfileBuilder import ConanProfileBuilder
from FslBuildGen.DataTypes import BuildRecipePipelineCommand, BuildRecipeValidateCommand
from FslBuildGen.Generator.GeneratorCMakeConfig import GeneratorCMakeConfig
from FslBuildGen.Generator.GeneratorInfo import GeneratorInfo
from FslBuildGen.Xml.XmlExperimentalRecipe import XmlExperimentalRecipe, XmlRecipePipeline
from FslBuildGen.Xml.XmlRecipePipelineFetchCommandConanInstall import XmlRecipePipelineFetchCommandConanInstall

# Conan packages are consumed through the find_package config files generated by Conan, so the recipe can not list the files itself
g_disallowedInstallationCommands = {BuildRecipeValidateCommand.AddHeaders, BuildRecipeValidateCommand.AddLib, BuildRecipeValidateCommand.AddDLL}


def UsesConan(pipeline: XmlRecipePipeline | None) -> bool:
    return TryGetConanInstallCommand(pipeline) is not None


def TryGetConanInstallCommand(pipeline: XmlRecipePipeline | None) -> XmlRecipePipelineFetchCommandConanInstall | None:
    if pipeline is None:
        return None
    for command in pipeline.CommandList:
        if command.CommandType == BuildRecipePipelineCommand.ConanInstall:
            if not isinstance(command, XmlRecipePipelineFetchCommandConanInstall):
                raise Exception("Internal error, command was not XmlRecipePipelineFetchCommandConanInstall")
            return command
    return None


def TryGetProfileHash(pipeline: XmlRecipePipeline | None, cmakeConfig: GeneratorCMakeConfig) -> str | None:
    """
    A hash of the Conan profiles the pipeline installs with. The profiles are derived from the generator setup so this catches changes
    that are not part of the recipe file itself, like a user set VS_TOOLSET_VERSION or changes to the profile generation.
    """
    command = TryGetConanInstallCommand(pipeline)
    if command is None:
        return None
    profiles = [ConanProfileBuilder.BuildFromCMakeConfig(cmakeConfig, config) for config in command.ConfigurationList]
    return hashlib.sha256("\n".join(profiles).encode("utf-8")).hexdigest()


def IsSupportedBy(generatorInfo: GeneratorInfo) -> bool:
    """Conan packages can only be consumed via find_package, which requires the CMake generator with find package support enabled"""
    return generatorInfo.IsCMakeGenerator and generatorInfo.AllowFindPackage


def ValidateRecipe(recipe: XmlExperimentalRecipe) -> None:
    """Raises a exception if a recipe that uses Conan is not setup the way Conan recipes are required to be"""
    if not UsesConan(recipe.Pipeline) or recipe.Pipeline is None:
        return

    if len(recipe.Pipeline.CommandList) != 1:
        raise Exception(f"Recipe '{recipe.ShortName}' a ConanInstall pipeline can not contain any other commands")
    if not recipe.Find:
        raise Exception(
            f"Recipe '{recipe.ShortName}' uses ConanInstall so it has to enable Find (set FindTargetName or FindVersion) as it is consumed via find_package"
        )
    if recipe.ValidateInstallation is not None:
        for command in recipe.ValidateInstallation.CommandList:
            if command.CommandType in g_disallowedInstallationCommands:
                raise Exception(
                    f"Recipe '{recipe.ShortName}' uses ConanInstall so its Installation can not contain '{command.CommandName}' as find_package supplies them"
                )
